[project]
name = "python-sgbd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyside6>=6.10.0",
    "tabulate>=0.9.0",
]
